'PUMLAMR
@startuml
!include ../../pumla_macros.puml
!include ../../modelrepo_json.puml
PUMLAReUsableAsset("curso", curso,class )

class curso <<entity>>{
  -nome() : int
  -departamento() : int
  -gradeCurricula() : int
}

PUMLAReUsableAssetFinalize()
@enduml
