'PUMLAMR
@startuml
!include ../../pumla_macros.puml
!include ../../modelrepo_json.puml
PUMLAReUsableAsset("RepositorioCursos", repositorioCursos,class )

class repositorioCursos{
  + inserir() : void
  + existe() : boolean
  + alterar() : void
  + consultar() : void
  + remover() : void
}

PUMLAReUsableAssetFinalize()
@enduml
