@startuml
skinparam actorStyle awesome
:Discente: -left-> (Re/matrícula)
:Discente: -right-> (Emitir comprovante de matrícula)
:Discente: -up-> (Acesso as notas do período)
:Discente: -down-> (Autenticação) 
note right of (Autenticação) : nesse caso o ator é o usuário do sistema
:Discente: -left-> (Aplicar para uma bolsa de monitoria/extensão/auxílio)
:Servidor: <-up- (Aplicar para uma bolsa de monitoria/extensão/auxílio)
:Discente: -right-> (Realizar trancamento do curso)
@enduml

@enduml