Person(aluno, "Aluno")
AddRelTag("u1d", $textColor="black", $lineColor="blue", $lineStyle = DashedLine())
AddRelTag("u1", $textColor="black", $lineColor="blue")
AddRelTag("u2d", $textColor="black", $lineColor="orange", $lineStyle = DashedLine())
AddRelTag("u2", $textColor="black", $lineColor="orange")
AddRelTag("u3d", $textColor="black", $lineColor="green", $lineStyle = DashedLine())
AddRelTag("u3", $textColor="black", $lineColor="green")
AddRelTag("u4d", $textColor="black", $lineColor="purple", $lineStyle = DashedLine())
AddRelTag("u4", $textColor="black", $lineColor="purple")
AddRelTag("u5d", $textColor="black", $lineColor="red", $lineStyle = DashedLine())
AddRelTag("u5", $textColor="black", $lineColor="red")
