@startuml C4_Elements
!include <C4/C4_Container>

Person(membrosDeProjeto, "Membro de projeto")
Person(liderDeProjeto, "Lider de projeto")
Person(aluno, "Aluno")

AddRelTag("u1d", $textColor="blue", $lineColor="blue", $lineStyle = DashedLine())
AddRelTag("u1", $textColor="blue", $lineColor="blue")
AddRelTag("u2d", $textColor="orange", $lineColor="orange", $lineStyle = DashedLine())
AddRelTag("u2", $textColor="orange", $lineColor="orange")
AddRelTag("u3d", $textColor="green", $lineColor="green", $lineStyle = DashedLine())
AddRelTag("u3", $textColor="green", $lineColor="green")
AddRelTag("u4d", $textColor="purple", $lineColor="purple", $lineStyle = DashedLine())
AddRelTag("u4", $textColor="purple", $lineColor="purple")
AddRelTag("u5d", $textColor="red", $lineColor="red", $lineStyle = DashedLine())
AddRelTag("u5", $textColor="red", $lineColor="red")

Container(spadis, "SPA-Perfil-discente")
Container(spadoc, "SPA-Perfil-docente")
ContainerDb(db, "DB", "", "")
Container(md, "ui-features-extensao", "", "")
System_Boundary(c2,Modulo Extensao){

System(statusSistema, "Pedidos")
System(notificacaoSistema, "Notificação")
System(descricaoSistema, "Detalhes")

' System(regrasNegocioSistema, "Regras de negócio")
System(filtragemSistema, "Filtragem")
System(consultaSistemas, "Consultas")
System(linksSistema, "Links")
System(formulariosSistema, "Formularios")
System(downloadsSistema, "Downloads")
System(newsSistema, "News")
}
'consultar projetos de extensao/homepage/lates/descricao que esteja ou nao associado, descricao
Rel(aluno, spadis, "ponto de entrada do sistema")
Rel(spadis, md, "consulta", "projetos de extensão que está ou não associado, lates, hoempage, descricao", $tags="u1")
Rel(md, consultaSistemas,"#1consulta", $tags="u1")
Rel(filtragemSistema, consultaSistemas,"#filtra", $tags="u1")
Rel(consultaSistemas, db,"#3acessa", $tags="u1")
Rel(db, consultaSistemas,"#4disponibiliza", $tags="u1")

'aplicar/sair/review/solicitar bolsa para projetos de extensão
Rel(spadis, md, "aplicacao/saída/review/bolsa no projeto de extensao", $tags="u2")
Rel(md, formulariosSistema,"#1preenche", $tags="u2")
Rel(formulariosSistema, db,"#2salva aplicacao", $tags="u2")
Rel(db, notificacaoSistema,"#3informa lider de projeto", $tags="u2")
Rel(db, statusSistema,"#4novo pedido criado", $tags="u2")
Rel(notificacaoSistema, spadoc,"$5notifica", $tags="u2")
Rel(spadoc, liderDeProjeto,"#6recebe notificacao", $tags="u2")
Rel(spadoc, membrosDeProjeto,"#6recebe notificacao", $tags="u2d")

'acompanhar pedidos
Rel(spadis, md, "acompanhar status", $tags="u3")
Rel(md, statusSistema, "#1acompanha", $tags="u3")
Rel(statusSistema, db,"#2requisita", $tags="u3")
Rel(db, statusSistema,"#3disponibilza", "",$tags="u3")
Rel(notificacaoSistema,statusSistema,"#4programar", $tags="u3d")
Rel(newsSistema,statusSistema,"#5fornece", $tags="u3d")


@enduml
