version: '3'

services:

  go_db:
    container_name: go_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    hostname: go_db

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"


  loginservice:
    container_name: loginservice
    build: 
      context: ./login_service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
      CONSUL_HOST: consul
      CONSUL_PORT: "8500"
    ports:
      - "8080:8080"
    volumes:
      - ./login_service:/go/src/app
    depends_on:
      - go_db
      - consul
    hostname: loginservice


  scholarshipservice:
    container_name: scholarshipservice
    build:
      context: ./scholarship_service
      dockerfile: dockerfile
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
      CONSUL_HOST: consul
      CONSUL_PORT: "8500"
    ports:
      - "8081:8081"
    volumes:
      - ./scholarship_service:/go/src/app
    depends_on:
      - go_db
      - consul
    hostname: scholarshipservice

  enrollmentservice:
    container_name: enrollmentservice
    build:
      context: ./enrollment_service
      dockerfile: dockerfile
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
      CONSUL_HOST: consul
      CONSUL_PORT: "8500"
    ports:
      - "8082:8082"
    volumes:
      - ./enrollment_service:/go/src/app
    depends_on:
      - go_db
      - consul
    hostname: enrollmentservice

  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: "8500"
    ports:
      - "8079:8079"
    volumes:
      - ./gateway:/go/src/app
    depends_on:
      - go_db
      - consul

  consul:
    container_name: consul
    build:
      context: ./consul
      dockerfile: dockerfile
    ports:
      - "8300:8300"
      - "8500:8500"
      - "8600:8600"
    hostname: consul


volumes:
  pgdata: {}