'PUMLAMR
@startuml
!include ../../pumla_macros.puml
!include ../../modelrepo_json.puml
PUMLAReUsableAsset("CadastroMatricula", cadastroMatricula,class )

class cadastroMatricula <<entity collection>>{
  
}

PUMLAReUsableAssetFinalize()
@enduml
