'PUMLAMR
@startuml
!include ../../pumla_macros.puml
!include ../../modelrepo_json.puml
PUMLAReUsableAsset("Tela Realizar matrícula", telaRealizarMatricula,class )

class telaRealizarMatricula <<boundary>>{
  +realizarMatricula() : void
  +selecionarDisciplina() : void
  + confirmarMatricula() : void
}

PUMLAReUsableAssetFinalize()
@enduml
