@startuml C4_Elements
!include <C4/C4_Container>

Person(aluno, "Aluno")

AddRelTag("u1d", $textColor="black", $lineColor="blue", $lineStyle = DashedLine())
AddRelTag("u1", $textColor="black", $lineColor="blue")
AddRelTag("u2d", $textColor="black", $lineColor="orange", $lineStyle = DashedLine())
AddRelTag("u2", $textColor="black", $lineColor="orange")
AddRelTag("u3d", $textColor="black", $lineColor="green", $lineStyle = DashedLine())
AddRelTag("u3", $textColor="black", $lineColor="green")
AddRelTag("u4d", $textColor="black", $lineColor="purple", $lineStyle = DashedLine())
AddRelTag("u4", $textColor="black", $lineColor="purple")
AddRelTag("u5d", $textColor="black", $lineColor="red", $lineStyle = DashedLine())
AddRelTag("u5", $textColor="black", $lineColor="red")

Container(spadis, "SPA-Perfil-discente")
ContainerDb(db, "DB", "", "")
Container(resource, "arquivo", "", "")
Container(md, "ui-features-ensino", "", "")
System_Boundary(c1,Módulo Ensino){

System(statusSistema, "Pedidos")
System(notificacaoSistema, "Notificação")
System(descricaoSistema, "Detalhes")

' System(regrasNegocioSistema, "Regras de negócio")
System(filtragemSistema, "Filtragem")
System(consultaSistemas, "Consultas")
System(linksSistema, "Links")
System(formulariosSistema, "Formularios")
System(downloadsSistema, "Downloads")
System(newsSistema, "News")
}
'filtrar projetos de extensão baseado em certo critério
Rel(aluno, spadis, "ponto de entrada do sistema")
Rel(spadis, md, "acesso e download de arquivos")
Rel(md, consultaSistemas,"consulta", "comprovante de matrícula,cronograma de cadeiras,sala de aula e horários, histórico escolar, declaração de vínculo, calendário acadêmico", $tags="u1")
Rel(consultaSistemas, db,"acesso a documento", $tags="u1")
Rel(db, consultaSistemas,"disponibiliza documento", $tags="u1")
Rel(consultaSistemas, downloadsSistema,"download do documento", $tags="u1d")
Rel(downloadsSistema, resource,"produz", $tags="u1")

'matricula nas cadeiras
Rel(spadis, md, "efetuar procedimentos de matricula")
Rel(md, consultaSistemas,"consulta de cadeiras para realizar matrícula", $tags="u2")
Rel(filtragemSistema, consultaSistemas,"filtrar cadeiras", $tags="u2d")
Rel(descricaoSistema, consultaSistemas,"detalhes da cadeira", $tags="u2d")
Rel(consultaSistemas, formulariosSistema,"confirmar cadeiras", $tags="u2")
Rel(formulariosSistema, db,"registrar cadeiras", $tags="u2")
Rel(db, notificacaoSistema,"confirmar sucesso na matricula", $tags="u2")
Rel(notificacaoSistema, statusSistema,"informar status do processo", $tags="u2")

'quando terá availação, faltas etc
Rel(spadis, md, "notícias de informações pertinentes")
Rel(md, consultaSistemas,"consulta de cadeiras para realizar matrícula", $tags="u2")
Rel(md, newsSistema,"informar sobre avaliacoes", "faltas, avaliações",$tags="u3")
Rel(notificacaoSistema,newsSistema,"programar notificação", $tags="u3d")

'consulta de informações relevantes ao curso
Rel(spadis, md, "consultas relevantes")
Rel(md, consultaSistemas,"consultas", "cursos, cadeiras obrigatórias, eletivas, ch, relacação de depedência entre cadeiras",$tags="u5")
Rel(filtragemSistema,consultaSistemas,"filtrar" ,$tags="u5d")
Rel(descricaoSistema,consultaSistemas,"detalhar" ,$tags="u5d")
Rel(consultaSistemas,db,"pedido de acesso" ,$tags="u5")
Rel(db,consultaSistemas,"acesso obtido" ,$tags="u5")


@enduml
